###
POST http://{{host}}:{{port}}/statistics/user/assignDate
Accept: application/json
Content-Type: application/json
Authorization: {{authToken}}

{
  "dateRange": {
    "start": "2018-10-26",
    "end": "2021-11-25"
  },
  "statisticsDate": "日"
}

> ../scripts/assertPass.js


###
GET http://{{host}}:{{port}}/statistics/user/recentDate?date=日
Accept: application/json
Content-Type: application/json
Authorization: {{authToken}}

> ../scripts/assertPass.js


###
GET http://{{host}}:{{port}}/statistics/user/total
Accept: application/json
Content-Type: application/json
Authorization: {{authToken}}

> ../scripts/assertPass.js