sudoku:
  name: SudokuX
  profile: D:/sudoku/uploadPath

#服务器开放端口
server:
  port: 8081

  undertow:
    direct-buffers: true
    threads:
      io: 1
      worker: 8

spring:
  profiles:
    active: @package.environment@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  #redis配置
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:

  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  #缓存配置
  cache:
    type: redis

  #应用监控
  boot:
    admin:
      client:
        username: admin
        password: 2233-qqaazz
        instance:
          name: sudoku-client

#mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.sudoku.project.model.entity
  configuration:
    use-generated-keys: true

#分页插件配置
pagehelper:
  reasonable: true

#日志配置
logging:
  level:
    com.sudoku: warn
    org.springframework: warn

#token配置
token:
  #令牌自定义标识
  header: Authorization
  #令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  #令牌有效期
  expireTime: 30
  #刷新令牌时间
  refreshTime: 20

#验证码配置
captcha:
  #长度
  width: 112
  #宽度
  height: 36
  #字符个数
  codeNumber: 4
  #干扰线个数
  lineCount: 100
  #有效期
  expireTime: 5
  #是否验证码
  enabled: false

#xxl-job
xxl:
  job:
    admin:
      #调度中心部署跟地址
      addresses: http://127.0.0.1:8085/xxl-job-admin
      #执行器通讯TOKEN
    executor:
      #执行器的AppName
      appname: sudoku-executor
    accessToken: zumin

#暴露应用状态
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  accessToken: 2233-qqaazz
