spring:
  datasource:
    #数据源配置
    username: sudoku
    password: root
    url: jdbc:mysql://rm-bp18y14er10ug8pk93o.mysql.rds.aliyuncs.com:3306/sudoku?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false

  #应用监控
  boot:
    admin:
      client:
        url: http://localhost:8088
        instance:
          service-base-url: http://localhost:8081

captcha:
  #关闭验证码
  enabled: false