spring:
  datasource:
    #数据源配置
    username: root
    password: '${SUDOKU_MYSQL_PASSWORD}'
    url: jdbc:mysql://localhost:3306/sudoku?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  #应用监控
  boot:
    admin:
      client:
        url: http://localhost:8088
        instance:
          service-url: http://localhost:8081

logging:
  level:
    #打印sql语句
    com.sudoku.project.mapper: debug

captcha:
  #开启验证码
  enabled: false