spring:
  datasource:
    #  数据源配置
    username: root
    password: '${SUDOKU_MYSQL_PASSWORD}'
    url: jdbc:mysql://localhost:3306/sudoku?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

logging:
  level:
    #打印sql语句
    com.sudoku.project.mapper: debug

captcha:
  #开启验证码
  enabled: true