spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: '${SUDOKU_MYSQL_PASSWORD}'
    url: jdbc:mysql://localhost:3306/sudoku?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:

  cache:
    type: ehcache

  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.sudoku.model.po
  configuration:
    use-generated-keys: true

pagehelper:
  reasonable: true

#logging:
#  level:
#    com.sudoku.mapper : debug