#服务器开放端口
server:
  port: 8081

spring:
  #  数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '${SUDOKU_MYSQL_PASSWORD}'
    url: jdbc:mysql://localhost:3306/sudoku?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  #redis配置
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:

  #缓存配置
  cache:
    type: redis

#mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.sudoku.project.model.entity
  configuration:
    use-generated-keys: true

#分页插件配置
pagehelper:
  reasonable: true

#日志配置
logging:
  level:
    com.sudoku: warn
    org.springframework: warn
    com.sudoku.project.mapper : debug

#token配置
token:
  #令牌自定义标识
  header: Authorization
  #令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  #令牌有效期
  expireTime: 30
  #刷新令牌时间
  refreshTime: 20

#验证码配置
captcha:
  #长度
  width: 112
  #宽度
  height: 36
  #字符个数
  codeNumber: 4
  #干扰线个数
  lineCount: 100
  #有效期
  expireTime: 5

#xxl-job
xxl:
  job:
    admin:
      #调度中心部署跟地址
      addresses: http://127.0.0.1:8085/xxl-job-admin
      #执行器通讯TOKEN
    executor:
      #执行器的AppName
      appname: sudoku-executor
    accessToken: zumin